<?php

namespace Corals\Modules\Payment\Common\database\seeds;

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('currencies')->delete();

        \DB::table('currencies')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'name' => 'UAE Dirham',
                    'code' => 'AED',
                    'symbol' => 'دإ‏',
                    'format' => 'دإ‏ 1,0.00',
                    'exchange_rate' => '3.673097',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            1 =>
                array(
                    'id' => 2,
                    'name' => 'Afghanistan, Afghani',
                    'code' => 'AFN',
                    'symbol' => '؋',
                    'format' => '؋1,0.00',
                    'exchange_rate' => '68.8225',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            2 =>
                array(
                    'id' => 3,
                    'name' => 'Albania, Lek',
                    'code' => 'ALL',
                    'symbol' => 'Lek',
                    'format' => '1,0.00Lek',
                    'exchange_rate' => '112.357515',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            3 =>
                array(
                    'id' => 4,
                    'name' => 'Armenian Dram',
                    'code' => 'AMD',
                    'symbol' => '&#1423;',
                    'format' => '1,0.00 &#1423;',
                    'exchange_rate' => '485.135',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            4 =>
                array(
                    'id' => 5,
                    'name' => 'Netherlands Antillian Guilder',
                    'code' => 'ANG',
                    'symbol' => 'ƒ',
                    'format' => 'ƒ1,0.00',
                    'exchange_rate' => '1.785537',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            5 =>
                array(
                    'id' => 6,
                    'name' => 'Angola, Kwanza',
                    'code' => 'AOA',
                    'symbol' => 'Kz',
                    'format' => 'Kz1,0.00',
                    'exchange_rate' => '165.9235',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            6 =>
                array(
                    'id' => 7,
                    'name' => 'Argentine Peso',
                    'code' => 'ARS',
                    'symbol' => '$',
                    'format' => '$ 1,0.00',
                    'exchange_rate' => '17.309393',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            7 =>
                array(
                    'id' => 8,
                    'name' => 'Australian Dollar',
                    'code' => 'AUD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1.313888',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            8 =>
                array(
                    'id' => 9,
                    'name' => 'Aruban Guilder',
                    'code' => 'AWG',
                    'symbol' => 'ƒ',
                    'format' => 'ƒ1,0.00',
                    'exchange_rate' => '1.786833',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            9 =>
                array(
                    'id' => 10,
                    'name' => 'Azerbaijanian Manat',
                    'code' => 'AZN',
                    'symbol' => '₼',
                    'format' => '1 0,00 ₼',
                    'exchange_rate' => '1.6985',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            10 =>
                array(
                    'id' => 11,
                    'name' => 'Bosnia and Herzegovina, Convertible Marks',
                    'code' => 'BAM',
                    'symbol' => 'КМ',
                    'format' => '1,0.00 КМ',
                    'exchange_rate' => '1.643914',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            11 =>
                array(
                    'id' => 12,
                    'name' => 'Barbados Dollar',
                    'code' => 'BBD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '2',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            12 =>
                array(
                    'id' => 13,
                    'name' => 'Bangladesh, Taka',
                    'code' => 'BDT',
                    'symbol' => '৳',
                    'format' => '৳ 1,0.',
                    'exchange_rate' => '82.368',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            13 =>
                array(
                    'id' => 14,
                    'name' => 'Bulgarian Lev',
                    'code' => 'BGN',
                    'symbol' => 'лв.',
                    'format' => '1 0,00 лв.',
                    'exchange_rate' => '1.645125',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            14 =>
                array(
                    'id' => 15,
                    'name' => 'Bahraini Dinar',
                    'code' => 'BHD',
                    'symbol' => '.د.',
                    'format' => '.د. 1,0.000',
                    'exchange_rate' => '0.376976',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            15 =>
                array(
                    'id' => 16,
                    'name' => 'Burundi Franc',
                    'code' => 'BIF',
                    'symbol' => 'FBu',
                    'format' => '1,0.FBu',
                    'exchange_rate' => '1755.05',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            16 =>
                array(
                    'id' => 17,
                    'name' => 'Bermudian Dollar',
                    'code' => 'BMD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            17 =>
                array(
                    'id' => 18,
                    'name' => 'Brunei Dollar',
                    'code' => 'BND',
                    'symbol' => '$',
                    'format' => '$1,0.',
                    'exchange_rate' => '1.347105',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            18 =>
                array(
                    'id' => 19,
                    'name' => 'Bolivia, Boliviano',
                    'code' => 'BOB',
                    'symbol' => 'Bs',
                    'format' => 'Bs 1,0.00',
                    'exchange_rate' => '6.911986',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            19 =>
                array(
                    'id' => 20,
                    'name' => 'Brazilian Real',
                    'code' => 'BRL',
                    'symbol' => 'R$',
                    'format' => 'R$ 1,0.00',
                    'exchange_rate' => '3.257225',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            20 =>
                array(
                    'id' => 21,
                    'name' => 'Bahamian Dollar',
                    'code' => 'BSD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            21 =>
                array(
                    'id' => 22,
                    'name' => 'Bhutan, Ngultrum',
                    'code' => 'BTN',
                    'symbol' => 'Nu.',
                    'format' => 'Nu. 1,0.0',
                    'exchange_rate' => '64.5066',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            22 =>
                array(
                    'id' => 23,
                    'name' => 'Botswana, Pula',
                    'code' => 'BWP',
                    'symbol' => 'P',
                    'format' => 'P1,0.00',
                    'exchange_rate' => '10.360258',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            23 =>
                array(
                    'id' => 24,
                    'name' => 'Belarussian Ruble',
                    'code' => 'BYR',
                    'symbol' => 'р.',
                    'format' => '1 0,00 р.',
                    'exchange_rate' => '0',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:15:04',
                ),
            24 =>
                array(
                    'id' => 25,
                    'name' => 'Belize Dollar',
                    'code' => 'BZD',
                    'symbol' => 'BZ$',
                    'format' => 'BZ$1,0.00',
                    'exchange_rate' => '2.010548',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            25 =>
                array(
                    'id' => 26,
                    'name' => 'Canadian Dollar',
                    'code' => 'CAD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1.26852',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            26 =>
                array(
                    'id' => 27,
                    'name' => 'Franc Congolais',
                    'code' => 'CDF',
                    'symbol' => 'FC',
                    'format' => '1,0.00FC',
                    'exchange_rate' => '1576',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            27 =>
                array(
                    'id' => 28,
                    'name' => 'Swiss Franc',
                    'code' => 'CHF',
                    'symbol' => 'CHF',
                    'format' => '1\'0.00 CHF',
                    'exchange_rate' => '0.97595',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            28 =>
                array(
                    'id' => 29,
                    'name' => 'Chilean Peso',
                    'code' => 'CLP',
                    'symbol' => '$',
                    'format' => '$ 1,0.00',
                    'exchange_rate' => '646.98',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            29 =>
                array(
                    'id' => 30,
                    'name' => 'China Yuan Renminbi',
                    'code' => 'CNY',
                    'symbol' => '¥',
                    'format' => '¥1,0.00',
                    'exchange_rate' => '6.6158',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            30 =>
                array(
                    'id' => 31,
                    'name' => 'Colombian Peso',
                    'code' => 'COP',
                    'symbol' => '$',
                    'format' => '$ 1,0.00',
                    'exchange_rate' => '3017.75',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            31 =>
                array(
                    'id' => 32,
                    'name' => 'Costa Rican Colon',
                    'code' => 'CRC',
                    'symbol' => '₡',
                    'format' => '₡1,0.00',
                    'exchange_rate' => '566.365',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            32 =>
                array(
                    'id' => 33,
                    'name' => 'Cuban Convertible Peso',
                    'code' => 'CUC',
                    'symbol' => 'CUC',
                    'format' => 'CUC1,0.00',
                    'exchange_rate' => '1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            33 =>
                array(
                    'id' => 34,
                    'name' => 'Cuban Peso',
                    'code' => 'CUP',
                    'symbol' => '$MN',
                    'format' => '$MN1,0.00',
                    'exchange_rate' => '25.5',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            34 =>
                array(
                    'id' => 35,
                    'name' => 'Cape Verde Escudo',
                    'code' => 'CVE',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '92.9',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            35 =>
                array(
                    'id' => 36,
                    'name' => 'Czech Koruna',
                    'code' => 'CZK',
                    'symbol' => 'Kč',
                    'format' => '1 0,00 Kč',
                    'exchange_rate' => '21.49',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            36 =>
                array(
                    'id' => 37,
                    'name' => 'Djibouti Franc',
                    'code' => 'DJF',
                    'symbol' => 'Fdj',
                    'format' => '1,0.Fdj',
                    'exchange_rate' => '178.77',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            37 =>
                array(
                    'id' => 38,
                    'name' => 'Danish Krone',
                    'code' => 'DKK',
                    'symbol' => 'kr.',
                    'format' => '1 0,00 kr.',
                    'exchange_rate' => '6.255485',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            38 =>
                array(
                    'id' => 39,
                    'name' => 'Dominican Peso',
                    'code' => 'DOP',
                    'symbol' => 'RD$',
                    'format' => 'RD$1,0.00',
                    'exchange_rate' => '48.183729',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            39 =>
                array(
                    'id' => 40,
                    'name' => 'Algerian Dinar',
                    'code' => 'DZD',
                    'symbol' => 'د.ج‏',
                    'format' => 'د.ج‏ 1,0.00',
                    'exchange_rate' => '114.697628',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            40 =>
                array(
                    'id' => 41,
                    'name' => 'Egyptian Pound',
                    'code' => 'EGP',
                    'symbol' => 'ج.م',
                    'format' => 'ج.م 1,0.00',
                    'exchange_rate' => '17.673',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            41 =>
                array(
                    'id' => 42,
                    'name' => 'Eritrea, Nakfa',
                    'code' => 'ERN',
                    'symbol' => 'Nfk',
                    'format' => '1,0.00Nfk',
                    'exchange_rate' => '15.250973',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            42 =>
                array(
                    'id' => 43,
                    'name' => 'Ethiopian Birr',
                    'code' => 'ETB',
                    'symbol' => 'ETB',
                    'format' => 'ETB1,0.00',
                    'exchange_rate' => '27.393',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            43 =>
                array(
                    'id' => 44,
                    'name' => 'Euro',
                    'code' => 'EUR',
                    'symbol' => '€',
                    'format' => '1.0,00 €',
                    'exchange_rate' => '0.84053',
                    'active' => 1,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            44 =>
                array(
                    'id' => 45,
                    'name' => 'Fiji Dollar',
                    'code' => 'FJD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '2.071754',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            45 =>
                array(
                    'id' => 46,
                    'name' => 'Falkland Islands Pound',
                    'code' => 'FKP',
                    'symbol' => '£',
                    'format' => '£1,0.00',
                    'exchange_rate' => '0.742255',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            46 =>
                array(
                    'id' => 47,
                    'name' => 'Pound Sterling',
                    'code' => 'GBP',
                    'symbol' => '£',
                    'format' => '£1,0.00',
                    'exchange_rate' => '0.742255',
                    'active' => 1,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            47 =>
                array(
                    'id' => 48,
                    'name' => 'Georgia, Lari',
                    'code' => 'GEL',
                    'symbol' => 'Lari',
                    'format' => '1 0,00 Lari',
                    'exchange_rate' => '2.710412',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            48 =>
                array(
                    'id' => 49,
                    'name' => 'Ghana Cedi',
                    'code' => 'GHS',
                    'symbol' => '₵',
                    'format' => '₵1,0.00',
                    'exchange_rate' => '4.497159',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            49 =>
                array(
                    'id' => 50,
                    'name' => 'Gibraltar Pound',
                    'code' => 'GIP',
                    'symbol' => '£',
                    'format' => '£1,0.00',
                    'exchange_rate' => '0.742255',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            50 =>
                array(
                    'id' => 51,
                    'name' => 'Gambia, Dalasi',
                    'code' => 'GMD',
                    'symbol' => 'D',
                    'format' => '1,0.00D',
                    'exchange_rate' => '47.4',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            51 =>
                array(
                    'id' => 52,
                    'name' => 'Guatemala, Quetzal',
                    'code' => 'GTQ',
                    'symbol' => 'Q',
                    'format' => 'Q1,0.00',
                    'exchange_rate' => '7.351959',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:04',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            52 =>
                array(
                    'id' => 53,
                    'name' => 'Guyana Dollar',
                    'code' => 'GYD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '207.955',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            53 =>
                array(
                    'id' => 54,
                    'name' => 'Hong Kong Dollar',
                    'code' => 'HKD',
                    'symbol' => 'HK$',
                    'format' => 'HK$1,0.00',
                    'exchange_rate' => '7.81201',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            54 =>
                array(
                    'id' => 55,
                    'name' => 'Honduras, Lempira',
                    'code' => 'HNL',
                    'symbol' => 'L.',
                    'format' => 'L. 1,0.00',
                    'exchange_rate' => '23.659145',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            55 =>
                array(
                    'id' => 56,
                    'name' => 'Croatian Kuna',
                    'code' => 'HRK',
                    'symbol' => 'kn',
                    'format' => '1,0.00 kn',
                    'exchange_rate' => '6.3502',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            56 =>
                array(
                    'id' => 57,
                    'name' => 'Haiti, Gourde',
                    'code' => 'HTG',
                    'symbol' => 'G',
                    'format' => 'G1,0.00',
                    'exchange_rate' => '64.237587',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            57 =>
                array(
                    'id' => 58,
                    'name' => 'Hungary, Forint',
                    'code' => 'HUF',
                    'symbol' => 'Ft',
                    'format' => '1 0,00 Ft',
                    'exchange_rate' => '263.818',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            58 =>
                array(
                    'id' => 59,
                    'name' => 'Indonesia, Rupiah',
                    'code' => 'IDR',
                    'symbol' => 'Rp',
                    'format' => 'Rp1,0.',
                    'exchange_rate' => '13521.099889',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            59 =>
                array(
                    'id' => 60,
                    'name' => 'New Israeli Shekel',
                    'code' => 'ILS',
                    'symbol' => '₪',
                    'format' => '₪ 1,0.00',
                    'exchange_rate' => '3.48543',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            60 =>
                array(
                    'id' => 61,
                    'name' => 'Indian Rupee',
                    'code' => 'INR',
                    'symbol' => '₹',
                    'format' => '1,0.00₹',
                    'exchange_rate' => '64.5105',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            61 =>
                array(
                    'id' => 62,
                    'name' => 'Iraqi Dinar',
                    'code' => 'IQD',
                    'symbol' => 'د.ع.‏',
                    'format' => 'د.ع.‏ 1,0.00',
                    'exchange_rate' => '1192.35',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            62 =>
                array(
                    'id' => 63,
                    'name' => 'Iranian Rial',
                    'code' => 'IRR',
                    'symbol' => '﷼',
                    'format' => '﷼ 1,0/00',
                    'exchange_rate' => '34782',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            63 =>
                array(
                    'id' => 64,
                    'name' => 'Iceland Krona',
                    'code' => 'ISK',
                    'symbol' => 'kr.',
                    'format' => '1,0. kr.',
                    'exchange_rate' => '103.25157',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            64 =>
                array(
                    'id' => 65,
                    'name' => 'Jamaican Dollar',
                    'code' => 'JMD',
                    'symbol' => 'J$',
                    'format' => 'J$1,0.00',
                    'exchange_rate' => '125.575',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            65 =>
                array(
                    'id' => 66,
                    'name' => 'Jordanian Dinar',
                    'code' => 'JOD',
                    'symbol' => 'د.ا.‏',
                    'format' => 'د.ا.‏ 1,0.000',
                    'exchange_rate' => '0.709503',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            66 =>
                array(
                    'id' => 67,
                    'name' => 'Japan, Yen',
                    'code' => 'JPY',
                    'symbol' => '¥',
                    'format' => '¥1,0.',
                    'exchange_rate' => '112.125',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            67 =>
                array(
                    'id' => 68,
                    'name' => 'Kenyan Shilling',
                    'code' => 'KES',
                    'symbol' => 'S',
                    'format' => 'S1,0.00',
                    'exchange_rate' => '103.016172',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            68 =>
                array(
                    'id' => 69,
                    'name' => 'Kyrgyzstan, Som',
                    'code' => 'KGS',
                    'symbol' => 'сом',
                    'format' => '1 0-00 сом',
                    'exchange_rate' => '69.707451',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            69 =>
                array(
                    'id' => 70,
                    'name' => 'Cambodia, Riel',
                    'code' => 'KHR',
                    'symbol' => '៛',
                    'format' => '1,0.៛',
                    'exchange_rate' => '4036.15',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            70 =>
                array(
                    'id' => 71,
                    'name' => 'Comoro Franc',
                    'code' => 'KMF',
                    'symbol' => 'CF',
                    'format' => '1,0.00CF',
                    'exchange_rate' => '414.125',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            71 =>
                array(
                    'id' => 72,
                    'name' => 'North Korean Won',
                    'code' => 'KPW',
                    'symbol' => '₩',
                    'format' => '₩1,0.',
                    'exchange_rate' => '900',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            72 =>
                array(
                    'id' => 73,
                    'name' => 'South Korea, Won',
                    'code' => 'KRW',
                    'symbol' => '₩',
                    'format' => '₩1,0.',
                    'exchange_rate' => '1083.3',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            73 =>
                array(
                    'id' => 74,
                    'name' => 'Kuwaiti Dinar',
                    'code' => 'KWD',
                    'symbol' => 'دينار‎‎‏',
                    'format' => 'دينار‎‎‏ 1,0.000',
                    'exchange_rate' => '0.301489',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            74 =>
                array(
                    'id' => 75,
                    'name' => 'Cayman Islands Dollar',
                    'code' => 'KYD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '0.833619',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            75 =>
                array(
                    'id' => 76,
                    'name' => 'Kazakhstan, Tenge',
                    'code' => 'KZT',
                    'symbol' => '₸',
                    'format' => '₸1 0-00',
                    'exchange_rate' => '331.37',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            76 =>
                array(
                    'id' => 77,
                    'name' => 'Laos, Kip',
                    'code' => 'LAK',
                    'symbol' => '₭',
                    'format' => '1,0.₭',
                    'exchange_rate' => '8325.35',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            77 =>
                array(
                    'id' => 78,
                    'name' => 'Lebanese Pound',
                    'code' => 'LBP',
                    'symbol' => 'ل.ل.‏',
                    'format' => 'ل.ل.‏ 1,0.00',
                    'exchange_rate' => '1516.4',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            78 =>
                array(
                    'id' => 79,
                    'name' => 'Sri Lanka Rupee',
                    'code' => 'LKR',
                    'symbol' => '₨',
                    'format' => '₨ 1,0.',
                    'exchange_rate' => '153.64',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            79 =>
                array(
                    'id' => 80,
                    'name' => 'Liberian Dollar',
                    'code' => 'LRD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '125.525',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            80 =>
                array(
                    'id' => 81,
                    'name' => 'Lesotho, Loti',
                    'code' => 'LSL',
                    'symbol' => 'M',
                    'format' => '1,0.00M',
                    'exchange_rate' => '13.765',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            81 =>
                array(
                    'id' => 82,
                    'name' => 'Libyan Dinar',
                    'code' => 'LYD',
                    'symbol' => 'د.ل.‏',
                    'format' => 'د.ل.‏1,0.000',
                    'exchange_rate' => '1.364095',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            82 =>
                array(
                    'id' => 83,
                    'name' => 'Moroccan Dirham',
                    'code' => 'MAD',
                    'symbol' => 'د.م.‏',
                    'format' => 'د.م.‏ 1,0.00',
                    'exchange_rate' => '9.394867',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            83 =>
                array(
                    'id' => 84,
                    'name' => 'Moldovan Leu',
                    'code' => 'MDL',
                    'symbol' => 'lei',
                    'format' => '1,0.00 lei',
                    'exchange_rate' => '17.199962',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            84 =>
                array(
                    'id' => 85,
                    'name' => 'Malagasy Ariary',
                    'code' => 'MGA',
                    'symbol' => 'Ar',
                    'format' => 'Ar1,0.',
                    'exchange_rate' => '3215.9',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            85 =>
                array(
                    'id' => 86,
                    'name' => 'Macedonia, Denar',
                    'code' => 'MKD',
                    'symbol' => 'ден.',
                    'format' => '1,0.00 ден.',
                    'exchange_rate' => '51.79',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            86 =>
                array(
                    'id' => 87,
                    'name' => 'Myanmar, Kyat',
                    'code' => 'MMK',
                    'symbol' => 'K',
                    'format' => 'K1,0.00',
                    'exchange_rate' => '1361.65',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            87 =>
                array(
                    'id' => 88,
                    'name' => 'Mongolia, Tugrik',
                    'code' => 'MNT',
                    'symbol' => '₮',
                    'format' => '₮1 0,00',
                    'exchange_rate' => '2439.11045',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            88 =>
                array(
                    'id' => 89,
                    'name' => 'Macao, Pataca',
                    'code' => 'MOP',
                    'symbol' => 'MOP$',
                    'format' => 'MOP$1,0.00',
                    'exchange_rate' => '8.047544',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            89 =>
                array(
                    'id' => 90,
                    'name' => 'Mauritania, Ouguiya',
                    'code' => 'MRO',
                    'symbol' => 'UM',
                    'format' => '1,0.00UM',
                    'exchange_rate' => '355.305',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            90 =>
                array(
                    'id' => 91,
                    'name' => 'Maltese Lira',
                    'code' => 'MTL',
                    'symbol' => '₤',
                    'format' => '₤1,0.00',
                    'exchange_rate' => '0',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:15:05',
                ),
            91 =>
                array(
                    'id' => 92,
                    'name' => 'Mauritius Rupee',
                    'code' => 'MUR',
                    'symbol' => '₨',
                    'format' => '₨1,0.00',
                    'exchange_rate' => '33.485333',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            92 =>
                array(
                    'id' => 93,
                    'name' => 'Maldives, Rufiyaa',
                    'code' => 'MVR',
                    'symbol' => 'MVR',
                    'format' => '1,0.0 MVR',
                    'exchange_rate' => '15.400126',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            93 =>
                array(
                    'id' => 94,
                    'name' => 'Malawi, Kwacha',
                    'code' => 'MWK',
                    'symbol' => 'MK',
                    'format' => 'MK1,0.00',
                    'exchange_rate' => '726.660938',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            94 =>
                array(
                    'id' => 95,
                    'name' => 'Mexican Peso',
                    'code' => 'MXN',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '18.625775',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            95 =>
                array(
                    'id' => 96,
                    'name' => 'Malaysian Ringgit',
                    'code' => 'MYR',
                    'symbol' => 'RM',
                    'format' => 'RM1,0.00',
                    'exchange_rate' => '4.089981',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            96 =>
                array(
                    'id' => 97,
                    'name' => 'Mozambique Metical',
                    'code' => 'MZN',
                    'symbol' => 'MT',
                    'format' => 'MT1,0.',
                    'exchange_rate' => '61',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            97 =>
                array(
                    'id' => 98,
                    'name' => 'Namibian Dollar',
                    'code' => 'NAD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '13.739931',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            98 =>
                array(
                    'id' => 99,
                    'name' => 'Nigeria, Naira',
                    'code' => 'NGN',
                    'symbol' => '₦',
                    'format' => '₦1,0.00',
                    'exchange_rate' => '360.1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            99 =>
                array(
                    'id' => 100,
                    'name' => 'Nicaragua, Cordoba Oro',
                    'code' => 'NIO',
                    'symbol' => 'C$',
                    'format' => 'C$ 1,0.00',
                    'exchange_rate' => '30.834',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            100 =>
                array(
                    'id' => 101,
                    'name' => 'Norwegian Krone',
                    'code' => 'NOK',
                    'symbol' => 'kr',
                    'format' => '1.0,00 kr',
                    'exchange_rate' => '8.283632',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            101 =>
                array(
                    'id' => 102,
                    'name' => 'Nepalese Rupee',
                    'code' => 'NPR',
                    'symbol' => '₨',
                    'format' => '₨1,0.00',
                    'exchange_rate' => '103.22',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            102 =>
                array(
                    'id' => 103,
                    'name' => 'New Zealand Dollar',
                    'code' => 'NZD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1.4521',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            103 =>
                array(
                    'id' => 104,
                    'name' => 'Rial Omani',
                    'code' => 'OMR',
                    'symbol' => '﷼',
                    'format' => '﷼ 1,0.000',
                    'exchange_rate' => '0.38484',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            104 =>
                array(
                    'id' => 105,
                    'name' => 'Panama, Balboa',
                    'code' => 'PAB',
                    'symbol' => 'B/.',
                    'format' => 'B/. 1,0.00',
                    'exchange_rate' => '1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            105 =>
                array(
                    'id' => 106,
                    'name' => 'Peru, Nuevo Sol',
                    'code' => 'PEN',
                    'symbol' => 'S/.',
                    'format' => 'S/. 1,0.00',
                    'exchange_rate' => '3.233584',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            106 =>
                array(
                    'id' => 107,
                    'name' => 'Papua New Guinea, Kina',
                    'code' => 'PGK',
                    'symbol' => 'K',
                    'format' => 'K1,0.00',
                    'exchange_rate' => '3.212984',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            107 =>
                array(
                    'id' => 108,
                    'name' => 'Philippine Peso',
                    'code' => 'PHP',
                    'symbol' => '₱',
                    'format' => '₱1,0.00',
                    'exchange_rate' => '50.258',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            108 =>
                array(
                    'id' => 109,
                    'name' => 'Pakistan Rupee',
                    'code' => 'PKR',
                    'symbol' => '₨',
                    'format' => '₨1,0.00',
                    'exchange_rate' => '105.405',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            109 =>
                array(
                    'id' => 110,
                    'name' => 'Poland, Zloty',
                    'code' => 'PLN',
                    'symbol' => 'zł',
                    'format' => '1 0,00 zł',
                    'exchange_rate' => '3.54235',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            110 =>
                array(
                    'id' => 111,
                    'name' => 'Paraguay, Guarani',
                    'code' => 'PYG',
                    'symbol' => '₲',
                    'format' => '₲ 1,0.00',
                    'exchange_rate' => '5670.85',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            111 =>
                array(
                    'id' => 112,
                    'name' => 'Qatari Rial',
                    'code' => 'QAR',
                    'symbol' => '﷼',
                    'format' => '﷼ 1,0.00',
                    'exchange_rate' => '3.6409',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            112 =>
                array(
                    'id' => 113,
                    'name' => 'Romania, New Leu',
                    'code' => 'RON',
                    'symbol' => 'lei',
                    'format' => '1,0.00 lei',
                    'exchange_rate' => '3.894307',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            113 =>
                array(
                    'id' => 114,
                    'name' => 'Serbian Dinar',
                    'code' => 'RSD',
                    'symbol' => 'Дин.',
                    'format' => '1,0.00 Дин.',
                    'exchange_rate' => '100.34',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            114 =>
                array(
                    'id' => 115,
                    'name' => 'Russian Ruble',
                    'code' => 'RUB',
                    'symbol' => '₽',
                    'format' => '1 0,00 ₽',
                    'exchange_rate' => '58.8891',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            115 =>
                array(
                    'id' => 116,
                    'name' => 'Rwanda Franc',
                    'code' => 'RWF',
                    'symbol' => 'RWF',
                    'format' => 'RWF 1 0,00',
                    'exchange_rate' => '858.18',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            116 =>
                array(
                    'id' => 117,
                    'name' => 'Saudi Riyal',
                    'code' => 'SAR',
                    'symbol' => '﷼',
                    'format' => '﷼ 1,0.00',
                    'exchange_rate' => '3.7503',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            117 =>
                array(
                    'id' => 118,
                    'name' => 'Solomon Islands Dollar',
                    'code' => 'SBD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '7.828472',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            118 =>
                array(
                    'id' => 119,
                    'name' => 'Seychelles Rupee',
                    'code' => 'SCR',
                    'symbol' => '₨',
                    'format' => '₨1,0.00',
                    'exchange_rate' => '13.4185',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            119 =>
                array(
                    'id' => 120,
                    'name' => 'Sudanese Dinar',
                    'code' => 'SDD',
                    'symbol' => 'LSd',
                    'format' => '1,0.00LSd',
                    'exchange_rate' => '0',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:15:05',
                ),
            120 =>
                array(
                    'id' => 121,
                    'name' => 'Swedish Krona',
                    'code' => 'SEK',
                    'symbol' => 'kr',
                    'format' => '1 0,00 kr',
                    'exchange_rate' => '8.3545',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            121 =>
                array(
                    'id' => 122,
                    'name' => 'Singapore Dollar',
                    'code' => 'SGD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1.346645',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            122 =>
                array(
                    'id' => 123,
                    'name' => 'Saint Helena Pound',
                    'code' => 'SHP',
                    'symbol' => '£',
                    'format' => '£1,0.00',
                    'exchange_rate' => '0.742255',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            123 =>
                array(
                    'id' => 124,
                    'name' => 'Sierra Leone, Leone',
                    'code' => 'SLL',
                    'symbol' => 'Le',
                    'format' => 'Le1,0.00',
                    'exchange_rate' => '7607.702542',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            124 =>
                array(
                    'id' => 125,
                    'name' => 'Somali Shilling',
                    'code' => 'SOS',
                    'symbol' => 'S',
                    'format' => 'S1,0.00',
                    'exchange_rate' => '578.62',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            125 =>
                array(
                    'id' => 126,
                    'name' => 'Surinam Dollar',
                    'code' => 'SRD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '7.448',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            126 =>
                array(
                    'id' => 127,
                    'name' => 'Sao Tome and Principe, Dobra',
                    'code' => 'STD',
                    'symbol' => 'Db',
                    'format' => 'Db1,0.00',
                    'exchange_rate' => '20597.575643',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            127 =>
                array(
                    'id' => 128,
                    'name' => 'El Salvador Colon',
                    'code' => 'SVC',
                    'symbol' => '₡',
                    'format' => '₡1,0.00',
                    'exchange_rate' => '8.7524',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            128 =>
                array(
                    'id' => 129,
                    'name' => 'Syrian Pound',
                    'code' => 'SYP',
                    'symbol' => '£',
                    'format' => '£ 1,0.00',
                    'exchange_rate' => '515.00999',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            129 =>
                array(
                    'id' => 130,
                    'name' => 'Swaziland, Lilangeni',
                    'code' => 'SZL',
                    'symbol' => 'E',
                    'format' => 'E1,0.00',
                    'exchange_rate' => '13.727983',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            130 =>
                array(
                    'id' => 131,
                    'name' => 'Thailand, Baht',
                    'code' => 'THB',
                    'symbol' => '฿',
                    'format' => '฿1,0.00',
                    'exchange_rate' => '32.591',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            131 =>
                array(
                    'id' => 132,
                    'name' => 'Tajikistan, Somoni',
                    'code' => 'TJS',
                    'symbol' => 'TJS',
                    'format' => '1 0;00 TJS',
                    'exchange_rate' => '8.817354',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            132 =>
                array(
                    'id' => 133,
                    'name' => 'Turkmenistani New Manat',
                    'code' => 'TMT',
                    'symbol' => 'm',
                    'format' => '1 0,m',
                    'exchange_rate' => '3.499986',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            133 =>
                array(
                    'id' => 134,
                    'name' => 'Tunisian Dinar',
                    'code' => 'TND',
                    'symbol' => 'د.ت.‏',
                    'format' => 'د.ت.‏ 1,0.000',
                    'exchange_rate' => '2.481',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            134 =>
                array(
                    'id' => 135,
                    'name' => 'Tonga, Paanga',
                    'code' => 'TOP',
                    'symbol' => 'T$',
                    'format' => 'T$1,0.00',
                    'exchange_rate' => '2.291837',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            135 =>
                array(
                    'id' => 136,
                    'name' => 'Turkish Lira',
                    'code' => 'TRY',
                    'symbol' => 'TL',
                    'format' => '₺1,0.00',
                    'exchange_rate' => '3.913204',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            136 =>
                array(
                    'id' => 137,
                    'name' => 'Trinidad and Tobago Dollar',
                    'code' => 'TTD',
                    'symbol' => 'TT$',
                    'format' => 'TT$1,0.00',
                    'exchange_rate' => '6.731841',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            137 =>
                array(
                    'id' => 138,
                    'name' => 'New Taiwan Dollar',
                    'code' => 'TWD',
                    'symbol' => 'NT$',
                    'format' => 'NT$1,0.00',
                    'exchange_rate' => '30.0165',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            138 =>
                array(
                    'id' => 139,
                    'name' => 'Tanzanian Shilling',
                    'code' => 'TZS',
                    'symbol' => 'TSh',
                    'format' => 'TSh1,0.00',
                    'exchange_rate' => '2241.6',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            139 =>
                array(
                    'id' => 140,
                    'name' => 'Ukraine, Hryvnia',
                    'code' => 'UAH',
                    'symbol' => '₴',
                    'format' => '1 0,00₴',
                    'exchange_rate' => '27.1125',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            140 =>
                array(
                    'id' => 141,
                    'name' => 'Uganda Shilling',
                    'code' => 'UGX',
                    'symbol' => 'USh',
                    'format' => 'USh1,0.00',
                    'exchange_rate' => '3634',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            141 =>
                array(
                    'id' => 142,
                    'name' => 'US Dollar',
                    'code' => 'USD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '1',
                    'active' => 1,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            142 =>
                array(
                    'id' => 143,
                    'name' => 'Peso Uruguayo',
                    'code' => 'UYU',
                    'symbol' => '$U',
                    'format' => '$U 1,0.00',
                    'exchange_rate' => '29.002688',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            143 =>
                array(
                    'id' => 144,
                    'name' => 'Uzbekistan Sum',
                    'code' => 'UZS',
                    'symbol' => 'сўм',
                    'format' => '1 0,00 сўм',
                    'exchange_rate' => '8098.1',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            144 =>
                array(
                    'id' => 145,
                    'name' => 'Venezuela Bolivares Fuertes',
                    'code' => 'VEF',
                    'symbol' => 'Bs. F.',
                    'format' => 'Bs. F. 1,0.00',
                    'exchange_rate' => '9.985022',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            145 =>
                array(
                    'id' => 146,
                    'name' => 'Viet Nam, Dong',
                    'code' => 'VND',
                    'symbol' => '₫',
                    'format' => '1,0.0 ₫',
                    'exchange_rate' => '22718.801563',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            146 =>
                array(
                    'id' => 147,
                    'name' => 'Vanuatu, Vatu',
                    'code' => 'VUV',
                    'symbol' => 'VT',
                    'format' => '1,0.VT',
                    'exchange_rate' => '107.205977',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            147 =>
                array(
                    'id' => 148,
                    'name' => 'Samoa, Tala',
                    'code' => 'WST',
                    'symbol' => 'WS$',
                    'format' => 'WS$1,0.00',
                    'exchange_rate' => '2.545678',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            148 =>
                array(
                    'id' => 149,
                    'name' => 'Franc CFA (XAF)',
                    'code' => 'XAF',
                    'symbol' => 'F.CFA',
                    'format' => '1,0.00 F.CFA',
                    'exchange_rate' => '551.351537',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            149 =>
                array(
                    'id' => 150,
                    'name' => 'East Caribbean Dollar',
                    'code' => 'XCD',
                    'symbol' => '$',
                    'format' => '$1,0.00',
                    'exchange_rate' => '2.70255',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            150 =>
                array(
                    'id' => 151,
                    'name' => 'Franc CFA (XOF)',
                    'code' => 'XOF',
                    'symbol' => 'F.CFA',
                    'format' => '1,0.00 F.CFA',
                    'exchange_rate' => '551.351537',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            151 =>
                array(
                    'id' => 152,
                    'name' => 'CFP Franc',
                    'code' => 'XPF',
                    'symbol' => 'F',
                    'format' => '1,0.00F',
                    'exchange_rate' => '100.301909',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            152 =>
                array(
                    'id' => 153,
                    'name' => 'Yemeni Rial',
                    'code' => 'YER',
                    'symbol' => '﷼',
                    'format' => '﷼ 1,0.00',
                    'exchange_rate' => '250.25',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            153 =>
                array(
                    'id' => 154,
                    'name' => 'South Africa, Rand',
                    'code' => 'ZAR',
                    'symbol' => 'R',
                    'format' => 'R 1,0.00',
                    'exchange_rate' => '13.74373',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
            154 =>
                array(
                    'id' => 155,
                    'name' => 'Zambia Kwacha',
                    'code' => 'ZMW',
                    'symbol' => 'ZK',
                    'format' => 'ZK1,0.00',
                    'exchange_rate' => '10.177886',
                    'active' => 0,
                    'created_at' => '2017-12-03 14:15:05',
                    'updated_at' => '2017-12-03 14:00:04',
                ),
        ));


    }
}